### PR TITLE
Update sensor.py

### PR DESCRIPTION
**Pull request by Imperial-Guard**
Rounding the total panel kWh output to maximum 2 decimals.

### CODE REVIEW

**Comment by ProudElm** [comment]
I was not sure wether to round or not. I chose not to round the numbers. Perhaps this is a personal thing or not. I alway think that any rounding can be done where you see the numbers (in a dashboard or something) and not where you create and or store the numbers. 
Perhaps if more users would like to just get the rounded numbers i will round them.

**Comment by Imperial-Guard** [comment]
Agree on that, since I'm using the sensors directly within Home Assistant it was for me that I could use it as a human readable format instead of creating new template sensors etc. 

I had some sensors with like 5 decimals which wouldn't make any sense in my opinion.

**Comment by ProudElm** [comment]
I understand. The number of decimals can be a bit much i agree.

For now im just glad that everything works. I will implemend it this weekend at my own system. Been running is for now on my DEV server. Main focus untill now was making sure it could work :-)

**Comment by ProudElm** [comment]
At this time i cannot do this, i use the exact value to check if the sensors needs updating. This should prevent some weird issues i saw. 
I will keep this issue in the back of my mind if i can find a way perhaps.

**Pull request closed without merging**
